---
- name: Install Apache on Ubuntu
  ansible.builtin.apt:
    name: apache2
    state: present

- name: Start the Apache service
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes



